async function importJSON(e){const f=e.target.files?.[0];if(!f)return;try{const data=normalize(JSON.parse(await f.text()));if(!confirm("¿Reemplazar los datos actuales?"))return;state=data;persist();render();toast("Respaldo importado")}catch{toast("Archivo JSON inválido")}}
function cloneMonth(){modal("#cloneTemplate",b=>{$("#cloneTarget",b).innerHTML=MONTHS.map((x,i)=>i===state.activeMonth?"":`<option value="${i}">${x}</option>`).join("");$("#cloneConfirm",b).onclick=()=>{const t=Number($("#cloneTarget",b).value),source=copy(state.months[state.activeMonth]);source.sections.forEach(s=>{s.id=uid("sec");s.items.forEach(i=>i.id=uid("item"));s.items.forEach(i=>i.amount=0)});source.openingBalance=0;state.months[t]=source;persist();render();close(b);toast(`Estructura duplicada a ${MONTHS[t]}`)}})}
function L(s,ctx=document){return ctx.querySelector(s)}
dom.ledger.addEventListener("click",e=>{const card=e.target.closest(".section-card");if(!card)return;const s=state.months[state.activeMonth].sections.find(x=>x.id===card.dataset.section);if(!s)return;const act=e.target.closest("[data-act]")?.dataset.act;if(act==="collapse"){s.collapsed=!s.collapsed;persist();renderLedger()}else if(act==="delete-section"&&confirm(`¿Eliminar “${s.title}”?`)){state.months[state.activeMonth].sections=state.months[state.activeMonth].sections.filter(x=>x.id!==s.id);persist();render();toast("Sección eliminada")}else if(act==="delete-item"){const row=e.target.closest(".row");s.items=s.items.filter(x=>x.id!==row.dataset.item);persist();render();toast("Concepto eliminado")}});
dom.ledger.addEventListener("change",e=>{const card=e.target.closest(".section-card");if(!card)return;const s=state.months[state.activeMonth].sections.find(x=>x.id===card.dataset.section);if(!s)return;const act=e.target.dataset.act,row=e.target.closest(".row");if(act==="section-name")s.title=e.target.value;if(act==="item-name"){const i=s.items.find(x=>x.id===row.dataset.item);if(i)i.name=e.target.value}if(act==="amount"){const i=s.items.find(x=>x.id===row.dataset.item);if(i)i.amount=amount(e.target.value);renderSummaryOnly()}persist()});
dom.ledger.addEventListener("keydown",e=>{if(e.key!=="Enter")return;const card=e.target.closest(".section-card"),s=state.months[state.activeMonth].sections.find(x=>x.id===card?.dataset.section);if(!s)return;if(e.target.dataset.act==="new-name"||e.target.dataset.act==="new-amount"){const body=card.querySelector(".section-body"),n=L('[data-act="new-name"]',body),a=L('[data-act="new-amount"]',body);if(!n.value.trim())return; s.items.push({id:uid("item"),name:n.value.trim(),amount:amount(a.value)});persist();renderLedger();renderSummaryOnly();setTimeout(()=>L('[data-act="new-name"]',card)?.focus())}});
function renderSummaryOnly(){const t=monthTotals(state.activeMonth);dom.balance.textContent=money(t.closing);dom.income.textContent=money(t.income);dom.expense.textContent=money(t.expense);dom.saving.textContent=money(t.saving);dom.opening.textContent=money(t.opening);dom.net.textContent=money(t.net);dom.savingRate.textContent=`${t.income?(t.saving/t.income*100).toFixed(1):"0.0"}%`;dom.expenseRate.textContent=`${t.income?(t.expense/t.income*100).toFixed(1):"0.0"}%`;renderCharts();renderFocus(t);renderGoalsMini();dom.monthNav.querySelectorAll("button").forEach(b=>b.querySelector("small").textContent=money(monthTotals(Number(b.dataset.month)).net))}
$("#sidebarBtn").onclick=()=>{dom.sidebar.classList.toggle("open");dom.overlay.hidden=!dom.sidebar.classList.contains("open")};dom.overlay.onclick=()=>{dom.sidebar.classList.remove("open");dom.overlay.hidden=true};
$("#prevMonthBtn").onclick=()=>{state.activeMonth=clamp(state.activeMonth-1,0,11);persist();render()};$("#nextMonthBtn").onclick=()=>{state.activeMonth=clamp(state.activeMonth+1,0,11);persist();render()};dom.monthNav.onclick=e=>{const b=e.target.closest("[data-month]");if(!b)return;state.activeMonth=Number(b.dataset.month);persist();render();if(innerWidth<=800){dom.sidebar.classList.remove("open");dom.overlay.hidden=true}};
$("#newSectionBtn").onclick=newSection;$("#goalsBtn").onclick=goals;$("#calendarBtn").onclick=calendar;$("#annualBtn").onclick=annual;$("#advisorBtn").onclick=advisor;$("#settingsBtn").onclick=settingsModal;$("#duplicateMonthBtn").onclick=cloneMonth;$("#themeBtn").onclick=()=>{settings.theme=document.body.classList.contains("dark")?"light":"dark";persist();applyTheme()};
function applyTheme(){let t=settings.theme;if(t==="system")t=matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light";document.body.classList.toggle("dark",t==="dark")}
window.addEventListener("keydown",e=>{if(e.key==="Escape"){const a=$$(".modal-backdrop.active");if(a.length)close(a[a.length-1])}});
applyTheme();persist();render();
