function migrate(x){if(!x||typeof x!=="object")return null;if(!Array.isArray(x.struct))return normalize(x);const s=emptyState();s.year=2026;s.activeMonth=Number.isInteger(x.month)?x.month:new Date().getMonth();s.months=Array.from({length:12},(_,m)=>{const mm=blankMonth(),old=Array.isArray(x.struct[m])?x.struct[m]:[];mm.sections=old.map(sec=>({id:String(sec.id||uid("sec")),title:String(sec.title||"Sección"),type:["income","expense","savings","debt"].includes(sec.type)?sec.type:"expense",collapsed:Boolean(sec.collapsed),debtTotal:amount(sec.debtTotal),debtRate:amount(sec.debtRate),items:(Array.isArray(sec.items)?sec.items:[]).map((name,i)=>({id:uid("item"),name:String(name||`Concepto ${i+1}`),amount:amount(x.data?.[`${m}-${sec.id}-${i}`])}))}));return mm});s.goals=(Array.isArray(x.goals)?x.goals:[]).map(g=>({id:uid("goal"),name:String(g.name||"Meta"),target:amount(g.target),contributions:{}}));s.events=(Array.isArray(x.events)?x.events:[]).map(e=>({id:uid("event"),name:String(e.name||"Evento"),date:dateKey(2026,clamp(amount(e.m)-1,0,11),clamp(amount(e.d)-1,0,30)+1),category:String(e.category||e.type||"General")}));return s}
function normalize(x){if(!x||typeof x!=="object")return emptyState();if(Array.isArray(x.struct))return migrate(x);const s=emptyState();s.year=Number(x.year)||s.year;s.activeMonth=Number.isInteger(x.activeMonth)?clamp(x.activeMonth,0,11):s.activeMonth;s.months=Array.from({length:12},(_,i)=>{const m=x.months?.[i]||blankMonth();return {openingBalance:amount(m.openingBalance),sections:(m.sections||[]).map(sec=>({id:String(sec.id||uid("sec")),title:String(sec.title||"Sección"),type:["income","expense","savings","debt"].includes(sec.type)?sec.type:"expense",collapsed:Boolean(sec.collapsed),debtTotal:amount(sec.debtTotal),debtRate:amount(sec.debtRate),items:(sec.items||[]).map(it=>({id:String(it.id||uid("item")),name:String(it.name||"Concepto"),amount:amount(it.amount)}))}))}});s.goals=(x.goals||[]).map(g=>({id:String(g.id||uid("goal")),name:String(g.name||"Meta"),target:amount(g.target),contributions:g.contributions&&typeof g.contributions==="object"?g.contributions:{}}));s.events=(x.events||[]).map(e=>({id:String(e.id||uid("event")),name:String(e.name||"Evento"),date:/^\d{4}-\d{2}-\d{2}$/.test(e.date)?e.date:today(),category:String(e.category||"General")}));s.version=V;return s}
let state=(()=>{try{const a=localStorage.getItem(STORE);if(a)return normalize(JSON.parse(a));const l=localStorage.getItem(LEGACY);if(l){const m=migrate(JSON.parse(l));if(m)localStorage.setItem(STORE,JSON.stringify(m));return m||emptyState()}}catch{}return emptyState()})();
const dom={sidebar:$("#sidebar"),overlay:$("#sidebarOverlay"),monthNav:$("#monthNav"),monthTitle:$("#monthTitle"),headerYear:$("#headerYear"),sidebarYear:$("#sidebarYear"),ledger:$("#ledger"),balance:$("#kpiBalance"),income:$("#kpiIncome"),expense:$("#kpiExpenses"),saving:$("#kpiSavings"),opening:$("#openingBalanceText"),net:$("#netFlowText"),savingRate:$("#savingsRateText"),expenseRate:$("#expenseRateText"),incomeSub:$("#kpiIncomeSub"),expenseSub:$("#kpiExpenseSub"),savingSub:$("#kpiSavingsSub"),longDate:$("#longDate"),chart:$("#expenseChart"),chartTotal:$("#chartTotal"),catBadge:$("#expenseCountBadge"),focus:$("#focusInsight"),goalMini:$("#goalMiniList"),host:$("#modalHost"),toast:$("#toast")};
let chart=null,annualCharts=[],toastTimer=null,cal={month:new Date().getMonth(),year:new Date().getFullYear(),day:null};
const persist=()=>{localStorage.setItem(STORE,JSON.stringify(state));localStorage.setItem(SETTINGS,JSON.stringify(settings))};
const monthTotals=m=>{const x=state.months[m];let income=0,expense=0,saving=0;(x?.sections||[]).forEach(s=>{const t=(s.items||[]).reduce((a,i)=>a+amount(i.amount),0);if(s.type==="income")income+=t;else if(s.type==="savings")saving+=t;else expense+=t});const opening=m===0?amount(x?.openingBalance||settings.yearOpeningBalance):(Number(x?.openingBalance)||monthTotals(m-1).closing);return {income,expense,saving,net:income-expense-saving,opening,closing:opening+income-expense-saving}};
const sectionTotal=s=>(s.items||[]).reduce((a,i)=>a+amount(i.amount),0);
const goalProgress=g=>{const total=Object.values(g.contributions||{}).reduce((a,v)=>a+amount(v),0);return {total,pct:g.target>0?clamp(total/g.target*100,0,100):0}};
function debtProjection(id,m){let bal=0,rate=0,last=null;for(let i=0;i<=m;i++){const s=state.months[i].sections.find(x=>x.id===id);if(!s)continue;bal=bal||amount(s.debtTotal);rate=amount(s.debtRate);const payment=sectionTotal(s),interest=bal*rate/100,capital=Math.max(0,payment-interest),end=Math.max(0,bal+interest-payment);last={balance:bal,interest,payment,capital,end};bal=end}return last}
